version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dynavest
      POSTGRES_USER: dynavest
      POSTGRES_PASSWORD: dynavest123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dynavest -d dynavest"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DynaVest Backend API
  backend:
    build:
      context: ./shuttle-backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://dynavest:dynavest123@postgres:5432/dynavest
      RUST_LOG: info
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: